spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always
    continue-on-error: true
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:postgresql://localhost:5432/naturaNovo?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgres

#spring:
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#        show_sql: true
#        format_sql: true
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    testWhileIdle: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#
#jwt:
#  secret: DbzComAbacate
#  expiration: 60000
